src/lib/Navbar.svelte
src/lib/Search.svelte
src/routes/__error.svelte

Todo
Something like this maybe
```svelte
<div transition:slide={{ duration: 35 }} />
```

Added animation, gave search some functionality and changed navbar urls

---

README.md
src/lib/Navbar.svelte
src/lib/Search.svelte
static/navbar_menu_icon.svg
svelte.config.js

Add search preview/suggestions

---

server.js

Added BeatLeader, Latest Curated maps and latest curated playlists endpoints to the webserver. Also updated most functions to be arrow functions.

Added new endpoints to server + arrow functions

---

src/app.scss
src/collections/posts/arknights-vol-3.md
src/collections/posts/one-month-wonders-vol-2-neon.md
src/collections/posts/re-zero-pack.md
src/collections/posts/takamachi-walk-song-pack.md
src/collections/posts/test-announcement-1.md
src/collections/posts/test-announcement-2.md
src/collections/posts/test-news-1.md
src/collections/posts/test-news-2.md
src/collections/posts/test-news-3.md
src/lib/AnnouncementHeader.svelte
src/lib/PostCards.svelte
src/routes/+layout.svelte
src/routes/+page.svelte
src/routes/+page.ts
src/routes/posts/+page.ts
src/types.ts
static/admin/config.yml

- Add announcement header component
- Update CMS fields to support sections within the Posts collection
- When creating a post with the CMS, admins will need to pick a section
- Update Post organization in +page.ts (pre-render TS) of homepage

Announcement header component & post organization for CMS

---

.gitignore
README.md
netlify.toml
package-lock.json
package.json

This PR will add more information on how to setup local development with netlify.
It does not include instruction for the backend and they are probably missing.
I'm not sure if this is the best or intended way to do this with Netlify, but it works. Happy about any feedback.

Adjust development details with Netlify

---

src/lib/PostListCard.svelte
src/maps.ts
src/routes/posts/+page.svelte
src/routes/posts/+page.ts
src/scss/variables.scss

We didn't have a mock for this so I just kinda winged it.

Add bare-bones posts listing

---

src/lib/Navbar.svelte
src/lib/QuickFilters.svelte

I deleted items that we don't have URLs for atm, added some that I felt were missing, and added URLs to items that didn't have one yet.

Nav rework

---

src/lib/PostCards.svelte
src/lib/PostListCard.svelte
src/routes/+page.svelte

Various post-related changes

---

src/app.scss
src/lib/Navbar.svelte
src/routes/+layout.svelte
src/routes/maps-of-the-week/[page]/+page.server.ts
src/routes/maps-of-the-week/[page]/+page.svelte
src/routes/posts/+page.svelte
src/routes/posts/+page.ts
src/routes/posts/[slug]/+page.server.ts
src/routes/posts/[slug]/+page.svelte

This currently pointed at the master branch, but should become an own branch I guess.
I'd make new branches from here.

Staging branch

---

src/routes/posts/[slug]/+page.svelte

I was testing this on an image that was already pretty dark, oops.

Fix border radius on dark overlay

---

src/lib/PaginationBar.svelte

Added "next" and "previous" buttons and cleaned up styling.

Pagination tweaks

---

src/lib/Navbar.svelte
src/lib/QuickFilters.svelte
src/lib/Search.svelte
src/routes/+page.svelte
src/scss/variables.scss

Lmk if you disagree with any of these.

Style changes

---

src/scss/variables.scss

Minor changes to font color issues noted here: https://discord.com/channels/452928402203344908/752003683780395069/1218381581471715420

Minor font color changes

---

src/lib/MapOfTheWeekSection.svelte
src/routes/+page.server.ts
src/routes/maps-of-the-week/[page]/+page.server.ts
src/types.ts

I had to turn off all formatters I could think of, as formatting will create whitespace where there shouldn't be whitespace.

Add collaborators to MOTW

---

src/app.html

Solves #94 without the nice to haves.

Insert google analytics snippets in header

---

src/lib/Search.svelte

This doesn't quite solve Issue 98 but I think it adds some good information

Enhancements to searches

---

src/lib/EventCards.svelte

Fix how dates are displayed in the events section in regard to local timezones

---

static/cms/motw/config.yml

Removes the editorial workflow from the MOTW config

CMS config change

---

src/lib/Leaderboards.svelte

This is the correct URL now but the request is blocked by CORS.

Fix leaderboard API

---

src/lib/MapCards.svelte
src/lib/Navbar.svelte
src/lib/OneClickDownloadButton.svelte
src/lib/PlaylistCards.svelte
src/lib/QuickFilter.svelte
src/lib/Search.svelte
src/lib/Uploader.svelte
src/lib/ZipDownloadButton.svelte
src/routes/community-hub/+page.svelte
src/scss/post-cards.scss
src/scss/variables.scss

Still planning to move both download buttons into one, and hiding it when not hovering.

Map card redesign

---

src/lib/Difficulties.svelte
src/lib/MapCards.svelte
src/types.ts

Hover effect for map cards

---

package-lock.json
package.json
src/lib/EventCards.svelte
src/lib/retrieveCommunityEvents.ts
src/types.ts
static/cms/admin/config.yml

Fix event time issues

---

src/lib/MapCards.svelte
src/lib/audio-player.ts

Add audio preview for map cards

---

src/lib/MapOfTheWeekSection.svelte
src/lib/PlaylistCards.svelte
src/routes/+page.server.ts
src/routes/maps-of-the-week/[page]/+page.server.ts
src/types.ts
static/cms/admin/config.yml
static/cms/motw/config.yml

Also makes it where MOTW doesn't actually need a showcase if one isn't made.

Add Zip Download option to Playlists and MOTW

---

src/collections/people/gmiz92.md
src/collections/people/sometimothy.md
src/collections/posts/getting-started.md
src/lib/PostPage.svelte
src/lib/SocialIcon.svelte
src/lib/iconMapping.ts
src/lib/retrieveCollectionData.ts
src/routes/community-hub/+page.svelte
src/routes/curation/+page.server.ts
src/routes/curation/+page.svelte
src/routes/diamonds-in-the-rough/+page.server.ts
src/routes/diamonds-in-the-rough/+page.svelte
src/routes/getting-started/+page.server.ts
src/routes/getting-started/+page.svelte
src/routes/getting-started/custom-songs/+page.server.ts
src/routes/getting-started/custom-songs/+page.svelte
src/routes/how-to-write-constructive-map-reviews/+page.server.ts
src/routes/how-to-write-constructive-map-reviews/+page.svelte
src/routes/installing-the-mod-guide-necessary-for-any-custom-songs/+page.server.ts
src/routes/installing-the-mod-guide-necessary-for-any-custom-songs/+page.svelte
src/routes/posts/[slug]/+page.server.ts
src/routes/posts/[slug]/+page.svelte
src/routes/the-beastsaber-mapping-awards/+page.server.ts
src/routes/the-beastsaber-mapping-awards/+page.svelte
src/types.ts
static/cms/admin/config.yml

Add authors to posts

---

src/collections/posts/custom-songs.md
src/collections/posts/installing-the-mod-guide-necessary-for-any-custom-songs.md
src/lib/PostPage.svelte
src/types.ts
static/cms/admin/config.yml

Add last updated for posts

---

src/app.scss
src/lib/Footer.svelte
src/routes/+layout.svelte
src/routes/playlists/fox-stevenson-pack/+page.svelte

Solves #155 
Do we want any other links here? Should we take any out?

Construct Footer

---

src/lib/MapCards.svelte
src/lib/PlaylistCards.svelte
src/lib/Search.svelte
src/lib/beatsaver-client.ts
src/lib/getFeaturedPlaylistCount.ts
src/lib/retrieveCollectionData.ts
src/routes/+page.server.ts
src/routes/curation-team/+page.svelte
src/routes/maps-of-the-week/[page]/+page.server.ts
src/routes/playlists/page/[page]/+page.server.ts

Would also resolve #95 unless I missed something.

Add BeatSaver Client

---

src/collections/community-events/ditr-6-release-date.md
src/collections/posts/diamonds-in-the-rough.md
src/routes/playlists/ditr-6/+page.svelte

I was in a hurry earlier so just fixing up some mistakes and small things I didn't like. Also updated 1 novice that _did_ finish the event

Really small optimizations to last PR

---

src/collections/posts/curator-applications-are-currently-open.md
src/routes/playlists/bsmg-5th-anniversary/+page.svelte
src/routes/playlists/fox-stevenson-pack/+page.svelte
src/routes/playlists/ive-switch-fitbeat-pack/+page.svelte

And post announcement for curator applications

Update existing Featured Packs to better format

---

README.md
src/collections/communities/beastsaber.md
src/collections/posts/hidden-features-of-beatsaver.md
src/collections/posts/the-beastsaber-mapping-awards.md
src/collections/posts/were-looking-for-authors.md
src/lib/Footer.svelte
src/routes/__error.svelte

Replaces "VJZHUbt" with "5VaEjFeuny"

Update/replace all Discord Invite Links

---

src/lib/CopyBSR.svelte
src/lib/MapCards.svelte
src/lib/MapOfTheWeekSection.svelte
src/lib/MapPreview.svelte

Adds the ability to copy the BSR code of the map for use on Twitch

Add Copy BSR element to MapCards

---

src/lib/Uploader.svelte

Fixes #184 in a not so aesthetically pleasing way but hopefully is only needed few and far between...

Add flex-wrap and overflow-wrap to uploader elements

---

static/cms/admin/dark.css
static/cms/admin/index.html
static/cms/index.html
static/cms/motw/config.yml
static/cms/motw/index.html

Adds Dark Mode layout for internal CMS pages (coincides with your system settings) and adds an auto log-out when the auth token expires. Also modifies some other minor styling and layout.

Additional modifications and improvements to the CMS

---

src/lib/MapCards.svelte
src/routes/+page.svelte

Use search api instead of latest as verified filter is kinda slow

---

src/lib/MapCards.svelte
src/types.ts

Hopefully this shouldn't be needed here but since the feature is available, would rather err on the side of caution.

Add NSFW blur to MapCards

---

src/lib/MapCards.svelte
src/lib/Search.svelte

I forgot map cover images show in Search as well so adding it here, too.

Expand NSFW blur to Search

---

src/lib/EventCards.svelte

Simple change so that it doesn't appear that something is missing. Says "No Upcoming Events Scheduled" if there are none.
Before
After

If no events scheduled, say that instead of nothing

---

src/app.scss
src/lib/Uploader.svelte

In response to #219 
Does a bit more by explaining the positional context and improve the curated by segment as well.
The application is very much improvable accessibility wise.
What do you think @michael-r-elp ?

Improve accessibility of the uploader and curator information

---

src/lib/MapOfTheWeekSection.svelte

Fix for interactive buttons overlapping MOTW reason text

---

src/lib/MapCards.svelte
src/lib/Uploader.svelte

Adds the ability to see collaborators/contributors on MapCards. The button/number will still display on mobile but made the `display: none;` for the tooltip/actual display of the collaborators since there's such limited space.
Closes #228

Show collaborators on MapCards
